/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FaBox: typeof import('./../ui/components/FaBox/index.vue')['default']
    FaCalc: typeof import('./../ui/components/FaCalc/index.vue')['default']
    FaDialog: typeof import('./../ui/components/FaDialog/index.vue')['default']
    FaIcon: typeof import('./../ui/components/FaIcon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysMenuBar: typeof import('./../components/sys-menu-bar/index.vue')['default']
  }
}
